### ISSUE TITLE
Duplicate keywords in primary header

### ISSUE THREAD

**Issue by jaymedina** [mmfausnaugh/tica#16]
Hi all, thanks for your work on this pipeline. 

I've found that there are duplicate primary header keywords for the order 1 deliveries of TICA: 

<img width="674" alt="image" src="https://user-images.githubusercontent.com/32107699/168136865-4ed651a8-7234-4bca-beab-5f12c71ec135.png">

File used is called: `hlsp_tica_tess_ffi_s0040-o1-00168414-cam4-ccd2_tess_v01_img.fits`

Not a huge deal, but it is affecting our pipeline as we try to implement TICA cutouts to our TESSCut API over at Space Telescope Science Institute. 

I can find a work-around for the deliveries that have already been made, but this is just a heads up for your future deliveries, in case it has not already been fixed.

**Comment by mmfausnaugh** [comment]
In v.1.1.2, I removed the 'extend' method for updating headers in wcs step2; this should be OBE anyway, since we now also run checks so that the code shouldn't run if these keywords already exist.

Closing issue.
